# Main plugin information
name: 'Treasury'
version: '${project.version}'
description: '${project.description}'
authors: ['lokka30']

# Dependencies
depend: []
softdepend: []

# General info for the plugin loader
main: 'me.lokka30.treasury.plugin.Treasury'
api-version: '1.13'
load: 'STARTUP'
loadbefore: []

# All registered base commands are listed here
commands:
  treasury:
    description: 'Manage the Treasury plugin.'

# All permissions used are listed here
permissions:
  treasury.command.treasury:
    description: 'Ability to run `/treasury`.'
    default: true
  treasury.command.treasury.help:
    description: 'Ability to run `/treasury help`.'
    default: true
  treasury.command.treasury.info:
    description: 'Ability to run `/treasury info`.'
    default: true