### Treasury
# Treasury is a modern code library for SpigotMC plugins.
# GitHub Repository: <https://github.com/lokka30/Treasury/>
#
### About this File
# Welcome to the settings.yml file, here you may configure
# parts of the plugin. For most servers, this file can be
# left alone as it usually contains settings tailored to
# more experienced server owners.
#
### Applying Changes
# Whenever you have finished making your changes to this
# configuration file, please save it, then run
# `/treasury reload` if your server is already running.

### Settings regarding the update checker.
# It is recommended you leave this enabled.
# The update checker makes a single check to the SpigotMC
# website to see if you are running the latest version of
# Treasury. It is asynchronous, and only sends a message
# if there is a new version available.
update-checker:

  ### Should the update checker be enabled?
  # This setting allows you to enable/disable the update checker.
  # Type: Boolean | Default: `true`
  enabled: true

### Settings regarding the debug logger.
# The debug logger is a system in Treasury only accessible
# to server administrators by default. It is used by Treasury
# developers on their test servers to assist in diagnosing any
# issues that may be present. It is recommended that all server
# owners leave this area alone as it will send a lot of spam to
# your console. Developers can configure what categories of debug
# logs they want to see to filter out all of the other messages.
debug:

  ### What debug-categories should be sent to the console?
  # This setting allows you to tune what categories of debug messages
  # will be sent to the server's console. The list functions as a
  # blacklist or whitelist, as set by the `mode`.
  enabled-categories:

    ### What list mode should the debug logger use?
    # `WHITELIST` - only the specified categories in the list
    #               will be enabled.
    # `BLACKLIST` - only the non-specified categories in the list
    #               will be enabled.
    # Type: `String` (DebugCategory constants) | Default: `WHITELIST`
    mode: 'WHITELIST'

    ### Contents of the debug logger categories list.
    # Add entries to the whitelist/blacklist here.
    # Use debug categories from the `DebugCategory` enum, available
    # at: <>
    # Type: `List<String>` (DebugCategory constants) | Default: `[ ]` (empty)
    list: [ ]

### Settings regarding the settings.yml file specifically.
# DO NOT TOUCH THESE SETTINGS. These settings are analysed by
# Treasury's file system to ensure you have an up-to-date file,
# adjusting any of these values can cause a malfunction.
# As values of these settings will change over time, no Default
# values will be supplied in this file's documentation.
file:

  ### Version of settings.yml.
  # DO NOT TOUCH THIS SETTING.
  # Type: `Integer`
  version: 1

  ### Version of the plugin that this file was generated with.
  # DO NOT TOUCH THIS SETTING.
  # It doesn't actually make any difference to modify this,
  # but it is useful for Treasury developers to see in case
  # there is an issue with your file.
  # Type: `String`
  generated-with: '${project.version}'